### ISSUE TITLE
Start date for video uploads is incorrect (local time zone is treated as UTC+0)

### ISSUE THREAD

**Issue by LukasKalbertodt** [Opencast-Moodle/moodle-block_opencast#165] opened 2021-03-16 12:28 UTC
Hello there!

I noticed that videos in Opencast uploaded via Moodle had strange start times, e.g. one hour in the future. I dug a bit into this code base and found this:

https://github.com/Opencast-Moodle/moodle-block_opencast/blob/6b129cac625ceb07351fa10df336efa00280a13e/addvideo.php#L123

The trailing `Z` in the string `2021-03-16T11:56:55.698Z` designates that the datetime is in the timezone UTC+0. But the code above just adds a trailing `Z` without adjusting the actual time at all, which is incorrect. As a specific example:

- I'm in timezone UTC+1 and my local time is 9:12. This means that it's 8:12 in UTC+0.
- I upload a video via Moodle and keep the default "now" start time. 
- This plugin adds a `Z` to my time and sends it to Opencast. (bug)
- Opencast now (correctly) interprets the time string as 9:12 UTC+0, which is 10:12 in my local time zone. 

That's why the time is wrong in Opencast. This plugin has to adjust the time instead by using the time zone of the user sending the POST request. Now I'm not sure what's the best way to do that, but that is the proper way as far as I can tell.

**Comment by lkiesow** [comment] 2021-03-18 15:02
This seems to be a duplicate of #148

**Comment by LukasKalbertodt** [comment] 2021-03-18 15:12
Woops, it is indeed. I tried finding an existing issue, but somehow didn't see that. This issue contains a bit more information than the previous one though, so I'll just keep it open for now. At maintainers: feel free to close.

**Closed** 2021-04-23 07:50 UTC
Labels: bug

**Comment by TamaraGunkel** [comment] 2021-04-23 07:52
Hi,
the bug should be fixed now. I simply convert the time to UTC.
The fix will be included in the next release.
