### ISSUE TITLE
Paella player caption and the caption button does not show up 

### ISSUE THREAD

**Issue by fishfree** [Opencast-Moodle/moodle-block_opencast#268] opened 2022-04-04 08:45 UTC
I upload a video by using block_opencast from Moodle to Opencast. The configured workflow in Opencast called Google/IBM attaching subtitle handler and sucessfully fetched the vtt file. In Opencast media module, the Paella player can show caption and the caption button as the screenshot below:
![image](https://user-images.githubusercontent.com/1741341/161507404-3571f766-cf5d-46d7-9814-d8327f9329c3.png)

But in Moodle Opencast episode, the caption and the button didn't show up, it was "display: none", as the screenshot below:
![image](https://user-images.githubusercontent.com/1741341/161507677-f5619dbd-8675-4d0b-bc1b-007a4a681eb9.png)

**Comment by ferishili** [comment] 2022-11-30 11:51
@fishfree
I am closing this issue as it is not related to this plugin, please try to double check if the problem is still there and write that in the mod_opencast issues list!
Thanks

**Closed by ferishili** 2022-11-30 11:51 UTC
