### ISSUE TITLE
Videos not loading

### ISSUE THREAD

**Issue by emmarichardson** [Opencast-Moodle/moodle-block_opencast#246] opened 2022-01-12 15:59 UTC
I am using the Opencast block (latest version) with Moodle 3.11.3 - I have Opencast Activity set up to display videos from a series that is on my server.  I am seeing some strange behavior where the video will not load but then if you go back to the page 10 minutes later or so, sometimes it will load.  I am getting a 403 error.  I am just wondering if anyone else has reported something similar or if there are any suggestions on where to start looking...

**Comment by emmarichardson** [comment] 2022-01-12 17:34
To add to this - it looks like this might be related to CORS - could it be an issue with the updated plugin?

**Comment by t-schroeder** [comment] 2022-01-12 18:49
To check if the problem is related to missing roles I think you can look at the me.json that's loaded when you open a page containing a video. It should list all roles that you currently have.

**Comment by emmarichardson** [comment] 2022-01-12 20:15
Thanks but I am not pulling me.json - would this file come from Moodle or Opencast?

**Comment by TamaraGunkel** [comment] 2022-02-08 12:05
me.json is comping from Opencast and contains information about who Opencast thinks you are

**Comment by justusdieckmann** [comment] 2024-03-01 00:02
Hey @emmarichardson,

I am currently going through older issues. Since the last activity on this issue is quite some time ago, I will close it for now. If it is still relevant to you, please do reopen the issue!

In this case, it sounds more like a opencast server configuration problem to me, but again, if this is still a current issue, we'll take a closer look at it :)

Cheers
Justus

**Closed by justusdieckmann** 2024-03-01 00:02 UTC
Labels: maintenance
